services:
  short:
    container_name: short-sam
    image: short-sam:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PUBLIC_SUPABASE_URL=${PUBLIC_SUPABASE_URL}
    user: 'node'
    # environment:
    #   - NODE_ENV=production
    #   - ORIGIN=http://localhost:3000
    # Points to a file with the sensitive environment variables
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3000:3000
